// AUTOGENERATED - DO NOT MODIFY
import ChatView from '../src/views/ChatView';import SettingsView from '../src/views/SettingsView';import OnboardingView from '../src/views/OnboardingView';

export * from '@stripe/ui-extension-sdk/version';
export const BUILD_TIME = '2026-02-12 15:33:03.509477 -0300 -03 m=+3.007036314';

export { 
  ChatView,	

  SettingsView,	

  OnboardingView	
 };

export default {
  "allowed_redirect_uris": [
    "https://dashboard.stripe.com/test/apps-oauth/com.javelin.ai",
    "https://dashboard.stripe.com/apps-oauth/com.javelin.ai"
  ],
  "connect_permissions": null,
  "distribution_type": "public",
  "icon": "./icon.png",
  "id": "com.javelin.ai",
  "name": "Javelin",
  "permissions": [
    {
      "permission": "customer_read",
      "purpose": "Read customer data to calculate business metrics and answer questions about your customer base"
    },
    {
      "permission": "invoice_read",
      "purpose": "Read invoice data to calculate revenue, MRR, and other billing metrics"
    },
    {
      "permission": "charge_read",
      "purpose": "Read charge data to analyze payment volume and revenue trends"
    },
    {
      "permission": "subscription_read",
      "purpose": "Read subscription data to calculate MRR, churn rate, and subscription analytics"
    },
    {
      "permission": "product_read",
      "purpose": "Read product data to break down revenue and metrics by product"
    },
    {
      "permission": "plan_read",
      "purpose": "Read price and plan data to analyze plan-level revenue and subscriber counts"
    },
    {
      "permission": "secret_write",
      "purpose": "Store and manage OAuth tokens securely via the Secret Store API"
    }
  ],
  "sandbox_install_compatible": true,
  "stripe_api_access_type": "oauth",
  "ui_extension": {
    "content_security_policy": {
      "connect-src": [
        "https://tecvycpmzcxxoqmtttjy.supabase.co/functions/v1/",
        "https://openrouter.ai/api/",
        "https://api.openai.com/v1/"
      ],
      "image-src": null,
      "purpose": "Connect to Supabase backend for data processing and LLM provider for AI-powered business intelligence"
    },
    "views": [
      {
        "component": "ChatView",
        "viewport": "stripe.dashboard.drawer.default"
      },
      {
        "component": "SettingsView",
        "viewport": "settings"
      },
      {
        "component": "OnboardingView",
        "viewport": "onboarding"
      }
    ]
  },
  "version": "0.0.1"
};
